--!strict

local TIMELINE_FPS: number = 60
local FINISH_FRAME: number = 600
local FINISH_TIME: number = FINISH_FRAME / TIMELINE_FPS
local TRANSITION_DURATION: number = 1.2
local LOCK_EXTRA_DURATION: number = 1.5
local ACK_TIMEOUT: number = 4
local LOCK_DURATION: number = FINISH_TIME + TRANSITION_DURATION + ACK_TIMEOUT + LOCK_EXTRA_DURATION

local MatchIntroConfig = {
	TIMELINE_FPS = TIMELINE_FPS,
	FINISH_FRAME = FINISH_FRAME,
	FINISH_TIME = FINISH_TIME,
	TRANSITION_DURATION = TRANSITION_DURATION,
	LOCK_DURATION = LOCK_DURATION,
	ACK_TIMEOUT = ACK_TIMEOUT,
}

return MatchIntroConfig
