--!strict

export type PerfectPassAction = "Emit" | "Enable" | "Disable" | "SetProperty"

export type PerfectPassEvent = {
	Frame: number,
	Action: PerfectPassAction,
	Path: string?,
	Property: string?,
	Value: any?,
	Amount: number?,
}

local MAX_FRAME: number = 516
local FPS: number = 60

local EVENTS: {PerfectPassEvent} = {
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.25869,
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.1",
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.2",
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.3",
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.4",
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.6",
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.7",
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.8",
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Workspace.JumpBack.9",
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.Blur",
		Property = "Size",
		Value = 4,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 1,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 1,
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 1.Torso.RightLines",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 1.Torso.RightLines1",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 1.Torso.Slashh",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 1.Torso.Dust",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 2.Torso.Dust",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 2.Torso.RightLines",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 2.Torso.RightLines1",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Workspace.Player 2.Torso.Slashh",
	},
	{
		Frame = 2,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.341665,
	},
	{
		Frame = 3,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.477636,
	},
	{
		Frame = 5,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.66539,
	},
	{
		Frame = 6,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.904234,
	},
	{
		Frame = 8,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.193939,
	},
	{
		Frame = 9,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.534689,
	},
	{
		Frame = 10,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.927055,
	},
	{
		Frame = 12,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.371952,
	},
	{
		Frame = 13,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.870625,
	},
	{
		Frame = 15,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.424606,
	},
	{
		Frame = 17,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.035706,
	},
	{
		Frame = 18,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.705978,
	},
	{
		Frame = 19,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.437689,
	},
	{
		Frame = 21,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.23328,
	},
	{
		Frame = 23,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 31.095293,
	},
	{
		Frame = 24,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 32.026348,
	},
	{
		Frame = 26,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 33.029022,
	},
	{
		Frame = 27,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 34.105759,
	},
	{
		Frame = 28,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.258724,
	},
	{
		Frame = 30,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.489632,
	},
	{
		Frame = 31,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.79953,
	},
	{
		Frame = 33,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 39.188534,
	},
	{
		Frame = 34,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 40.65551,
	},
	{
		Frame = 36,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 42.197689,
	},
	{
		Frame = 38,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.810261,
	},
	{
		Frame = 39,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 45.485859,
	},
	{
		Frame = 41,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 47.214092,
	},
	{
		Frame = 42,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 48.980961,
	},
	{
		Frame = 44,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 50.768486,
	},
	{
		Frame = 45,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 52.554165,
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.1",
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.2",
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.3",
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.4",
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.6",
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.7",
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.8",
	},
	{
		Frame = 45,
		Action = "Disable",
		Path = "Workspace.JumpBack.9",
	},
	{
		Frame = 45,
		Action = "Enable",
		Path = "Lighting.Blur",
	},
	{
		Frame = 45,
		Action = "SetProperty",
		Path = "Lighting.Blur",
		Property = "Size",
		Value = 0,
	},
	{
		Frame = 46,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 54.310925,
	},
	{
		Frame = 48,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 56.007015,
	},
	{
		Frame = 48,
		Action = "SetProperty",
		Path = "Workspace.Drag",
		Property = "CFrame",
		Value = {-3.702312, 0.407409, 6.559526, 0, 0, -1, 0, 1, 0, 1, 0, 0},
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.Dust",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.Dust2",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.DustColor",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.DustColor1",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.DustColor2",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.DustColor3",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.DustFlip",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.DustUp",
	},
	{
		Frame = 48,
		Action = "Enable",
		Path = "Workspace.Drag.DragEffect.RockGroup",
	},
	{
		Frame = 49,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 57.606441,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.1",
		Amount = 5,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.2",
		Amount = 1,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.3",
		Amount = 15,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.4",
		Amount = 7,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.5",
		Amount = 2,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.Attachment.Out_Impact",
		Amount = 3,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.smok1",
		Amount = 10,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.smok2",
		Amount = 10,
	},
	{
		Frame = 49,
		Action = "Emit",
		Path = "Workspace.FALL.smok3",
		Amount = 10,
	},
	{
		Frame = 49,
		Action = "SetProperty",
		Path = "Workspace.FALL",
		Property = "CFrame",
		Value = {-3.265832, 0.081402, 6.59866, 1, 0, 0, 0, 1, 0, 0, 0, 1},
	},
	{
		Frame = 50,
		Action = "SetProperty",
		Path = "Lighting.Blur",
		Property = "Size",
		Value = 15,
	},
	{
		Frame = 51,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 59.069637,
	},
	{
		Frame = 53,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 60.354767,
	},
	{
		Frame = 54,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 61.419304,
	},
	{
		Frame = 56,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 62.222103,
	},
	{
		Frame = 57,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 62.725811,
	},
	{
		Frame = 59,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 62.899261,
	},
	{
		Frame = 60,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 60.37328,
	},
	{
		Frame = 61,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 54.55632,
	},
	{
		Frame = 61,
		Action = "SetProperty",
		Path = "Workspace.Drag",
		Property = "CFrame",
		Value = {-4.241849, 0.407409, 9.468016, 0, 0, -1, 0, 1, 0, 1, 0, 0},
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.Dust",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.Dust2",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.DustColor",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.DustColor1",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.DustColor2",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.DustColor3",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.DustFlip",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.DustUp",
	},
	{
		Frame = 61,
		Action = "Disable",
		Path = "Workspace.Drag.DragEffect.RockGroup",
	},
	{
		Frame = 61,
		Action = "SetProperty",
		Path = "Lighting.Blur",
		Property = "Size",
		Value = 4,
	},
	{
		Frame = 63,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 47.966106,
	},
	{
		Frame = 65,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 42.1203,
	},
	{
		Frame = 66,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.523701,
	},
	{
		Frame = 68,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 34.043575,
	},
	{
		Frame = 69,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 31.487375,
	},
	{
		Frame = 70,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.717939,
	},
	{
		Frame = 72,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.657751,
	},
	{
		Frame = 74,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.294395,
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.1",
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.2",
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.3",
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.4",
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.6",
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.7",
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.8",
	},
	{
		Frame = 74,
		Action = "Enable",
		Path = "Workspace.JumpBack.9",
	},
	{
		Frame = 75,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.61738,
	},
	{
		Frame = 76,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.484274,
	},
	{
		Frame = 78,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.755367,
	},
	{
		Frame = 80,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 32.266224,
	},
	{
		Frame = 81,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 33.782993,
	},
	{
		Frame = 83,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 34.977844,
	},
	{
		Frame = 84,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.758755,
	},
	{
		Frame = 85,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.312447,
	},
	{
		Frame = 87,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.676838,
	},
	{
		Frame = 89,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.901005,
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.1",
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.2",
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.3",
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.4",
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.6",
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.7",
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.8",
	},
	{
		Frame = 89,
		Action = "Disable",
		Path = "Workspace.JumpBack.9",
	},
	{
		Frame = 90,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.040844,
	},
	{
		Frame = 91,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.155842,
	},
	{
		Frame = 93,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.307373,
	},
	{
		Frame = 95,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.558929,
	},
	{
		Frame = 96,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.961807,
	},
	{
		Frame = 98,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 38.505947,
	},
	{
		Frame = 99,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 39.165085,
	},
	{
		Frame = 100,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 39.91077,
	},
	{
		Frame = 102,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 40.710709,
	},
	{
		Frame = 104,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 41.527325,
	},
	{
		Frame = 105,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 42.316917,
	},
	{
		Frame = 106,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.029537,
	},
	{
		Frame = 108,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.609947,
	},
	{
		Frame = 110,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.999897,
	},
	{
		Frame = 111,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 44.14188,
	},
	{
		Frame = 113,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 44.136707,
	},
	{
		Frame = 114,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 44.100525,
	},
	{
		Frame = 115,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 44.002594,
	},
	{
		Frame = 116,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0,
	},
	{
		Frame = 117,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.813072,
	},
	{
		Frame = 119,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.503994,
	},
	{
		Frame = 120,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.050541,
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Embers1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Mass1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Smoke2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Smoke3",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Smoke4",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Smoke5",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Smoke6",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.Smoke7",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.debris",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.debris1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.flare2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.smoke",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Embers1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Mass1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Smoke3",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Smoke2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Smoke4",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Smoke5",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Smoke6",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.Smoke7",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.debris",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.debris1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.flare2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Arm.smoke",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Embers1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Mass1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Smoke2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Smoke3",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Smoke4",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Smoke5",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Smoke6",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.Smoke7",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.debris",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.debris1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.flare2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.smoke",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Left Leg.smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Embers1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Mass1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Smoke2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Smoke3",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Smoke4",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Smoke5",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Smoke6",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.Smoke7",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.debris",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.debris1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.flare2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.smoke",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Embers1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Mass1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Smoke2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Smoke3",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Smoke4",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Smoke5",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Smoke6",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.Smoke7",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.debris",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.debris1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.flare2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.smoke",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Leg.smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Embers1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Mass1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Smoke1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Smoke2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Smoke3",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Smoke4",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Smoke5",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Smoke6",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.Smoke7",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.debris",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.debris1",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.flare2",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.smoke",
	},
	{
		Frame = 121,
		Action = "Enable",
		Path = "Workspace.Player 10.Torso.smoke1",
	},
	{
		Frame = 122,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 42.432564,
	},
	{
		Frame = 123,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 41.636005,
	},
	{
		Frame = 125,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 40.654213,
	},
	{
		Frame = 126,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 39.488735,
	},
	{
		Frame = 128,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 38.149532,
	},
	{
		Frame = 128,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.8,
	},
	{
		Frame = 128,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Offset",
		Value = 1,
	},
	{
		Frame = 129,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.654461,
	},
	{
		Frame = 130,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.028015,
	},
	{
		Frame = 132,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 33.299507,
	},
	{
		Frame = 133,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 31.500961,
	},
	{
		Frame = 135,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.664835,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeR.Star1",
		Amount = 1.35,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeR.Star1a",
		Amount = 1.35,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeR.Wave",
		Amount = 2.7,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeR.Wave1",
		Amount = 2.7,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeR.Wave2",
		Amount = 10.8,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeL.Star1",
		Amount = 1.35,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeL.Star1a",
		Amount = 1.35,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeL.Wave",
		Amount = 2.7,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeL.Wave1",
		Amount = 2.7,
	},
	{
		Frame = 135,
		Action = "Emit",
		Path = "Workspace.Player 10.Head.EyeL.Wave2",
		Amount = 10.8,
	},
	{
		Frame = 135,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.EyeR.EyeGlow",
	},
	{
		Frame = 135,
		Action = "Enable",
		Path = "Workspace.Player 10.Head.EyeL.EyeGlow",
	},
	{
		Frame = 137,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.822102,
	},
	{
		Frame = 138,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.000616,
	},
	{
		Frame = 140,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.224081,
	},
	{
		Frame = 141,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.490982,
	},
	{
		Frame = 141,
		Action = "Enable",
		Path = "Workspace.run streaks.1",
	},
	{
		Frame = 141,
		Action = "Enable",
		Path = "Workspace.run streaks.2",
	},
	{
		Frame = 141,
		Action = "Enable",
		Path = "Workspace.run streaks.4",
	},
	{
		Frame = 141,
		Action = "Enable",
		Path = "Workspace.run streaks.6",
	},
	{
		Frame = 141,
		Action = "Enable",
		Path = "Workspace.run streaks.7",
	},
	{
		Frame = 143,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 13.978908,
	},
	{
		Frame = 144,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 10.415447,
	},
	{
		Frame = 145,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 8.425336,
	},
	{
		Frame = 147,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 7.489115,
	},
	{
		Frame = 148,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 7.090666,
	},
	{
		Frame = 150,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.846466,
	},
	{
		Frame = 152,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.706363,
	},
	{
		Frame = 153,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.636621,
	},
	{
		Frame = 153,
		Action = "SetProperty",
		Path = "Workspace.run streaks.1",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 153,
		Action = "SetProperty",
		Path = "Workspace.run streaks.2",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 153,
		Action = "SetProperty",
		Path = "Workspace.run streaks.4",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 153,
		Action = "SetProperty",
		Path = "Workspace.run streaks.6",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 153,
		Action = "SetProperty",
		Path = "Workspace.run streaks.7",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 155,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.61129,
	},
	{
		Frame = 156,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.607687,
	},
	{
		Frame = 158,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.613279,
	},
	{
		Frame = 159,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.628662,
	},
	{
		Frame = 160,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.65178,
	},
	{
		Frame = 162,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.680582,
	},
	{
		Frame = 163,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.712981,
	},
	{
		Frame = 165,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.746823,
	},
	{
		Frame = 167,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.779868,
	},
	{
		Frame = 168,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.809792,
	},
	{
		Frame = 170,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.834191,
	},
	{
		Frame = 171,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.850618,
	},
	{
		Frame = 173,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.856629,
	},
	{
		Frame = 174,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.851224,
	},
	{
		Frame = 175,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.836597,
	},
	{
		Frame = 177,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.815155,
	},
	{
		Frame = 178,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.789297,
	},
	{
		Frame = 180,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.76138,
	},
	{
		Frame = 182,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.73369,
	},
	{
		Frame = 183,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.708446,
	},
	{
		Frame = 185,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.687798,
	},
	{
		Frame = 186,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.673859,
	},
	{
		Frame = 188,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.668737,
	},
	{
		Frame = 188,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.8,
	},
	{
		Frame = 189,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.1206,
	},
	{
		Frame = 189,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.55,
	},
	{
		Frame = 190,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.501873,
	},
	{
		Frame = 192,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.88003,
	},
	{
		Frame = 193,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.254087,
	},
	{
		Frame = 195,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.623062,
	},
	{
		Frame = 197,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.985968,
	},
	{
		Frame = 198,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.34182,
	},
	{
		Frame = 200,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.689659,
	},
	{
		Frame = 201,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.028551,
	},
	{
		Frame = 203,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.357595,
	},
	{
		Frame = 204,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.675949,
	},
	{
		Frame = 205,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.982817,
	},
	{
		Frame = 207,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.277472,
	},
	{
		Frame = 208,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.559261,
	},
	{
		Frame = 210,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.82762,
	},
	{
		Frame = 212,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.08206,
	},
	{
		Frame = 213,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.322193,
	},
	{
		Frame = 215,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.547724,
	},
	{
		Frame = 216,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.758465,
	},
	{
		Frame = 218,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.954309,
	},
	{
		Frame = 219,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.135277,
	},
	{
		Frame = 220,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.30146,
	},
	{
		Frame = 222,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.453068,
	},
	{
		Frame = 223,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.590393,
	},
	{
		Frame = 225,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.713814,
	},
	{
		Frame = 227,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.823792,
	},
	{
		Frame = 228,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.920872,
	},
	{
		Frame = 230,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.005661,
	},
	{
		Frame = 231,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.078833,
	},
	{
		Frame = 233,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.141117,
	},
	{
		Frame = 234,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.193285,
	},
	{
		Frame = 235,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.236166,
	},
	{
		Frame = 237,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.270613,
	},
	{
		Frame = 238,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.297503,
	},
	{
		Frame = 240,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.317749,
	},
	{
		Frame = 242,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.332281,
	},
	{
		Frame = 243,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.342028,
	},
	{
		Frame = 244,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.347946,
	},
	{
		Frame = 246,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.350981,
	},
	{
		Frame = 248,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.352106,
	},
	{
		Frame = 249,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.352264,
	},
	{
		Frame = 250,
		Action = "SetProperty",
		Path = "Workspace.run streaks.1",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 250,
		Action = "SetProperty",
		Path = "Workspace.run streaks.2",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 250,
		Action = "SetProperty",
		Path = "Workspace.run streaks.4",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 250,
		Action = "SetProperty",
		Path = "Workspace.run streaks.6",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 250,
		Action = "SetProperty",
		Path = "Workspace.run streaks.7",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 251,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.30747,
	},
	{
		Frame = 251,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 251,
		Action = "Enable",
		Path = "Lighting.CutOut",
	},
	{
		Frame = 251,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 252,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.186695,
	},
	{
		Frame = 252,
		Action = "Enable",
		Path = "Workspace.Player 2.Torso.Dust",
	},
	{
		Frame = 252,
		Action = "Enable",
		Path = "Workspace.Player 2.Torso.RightLines",
	},
	{
		Frame = 252,
		Action = "Enable",
		Path = "Workspace.Player 2.Torso.RightLines1",
	},
	{
		Frame = 252,
		Action = "Enable",
		Path = "Workspace.Player 2.Torso.Slashh",
	},
	{
		Frame = 253,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.010857,
	},
	{
		Frame = 255,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.800694,
	},
	{
		Frame = 255,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Contrast",
		Value = -5,
	},
	{
		Frame = 255,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Saturation",
		Value = -1,
	},
	{
		Frame = 257,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.576069,
	},
	{
		Frame = 258,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.355587,
	},
	{
		Frame = 259,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.156538,
	},
	{
		Frame = 261,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.99511,
	},
	{
		Frame = 263,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.886829,
	},
	{
		Frame = 263,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 263,
		Action = "Disable",
		Path = "Lighting.CutOut",
	},
	{
		Frame = 263,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 264,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.847191,
	},
	{
		Frame = 266,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.862709,
	},
	{
		Frame = 267,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.90757,
	},
	{
		Frame = 268,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.979362,
	},
	{
		Frame = 270,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.075815,
	},
	{
		Frame = 270,
		Action = "SetProperty",
		Path = "Workspace.run streaks.1",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 270,
		Action = "SetProperty",
		Path = "Workspace.run streaks.2",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 270,
		Action = "SetProperty",
		Path = "Workspace.run streaks.4",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 270,
		Action = "SetProperty",
		Path = "Workspace.run streaks.6",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 270,
		Action = "SetProperty",
		Path = "Workspace.run streaks.7",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 272,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.194727,
	},
	{
		Frame = 273,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.333948,
	},
	{
		Frame = 274,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.491297,
	},
	{
		Frame = 276,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.664555,
	},
	{
		Frame = 278,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.851412,
	},
	{
		Frame = 279,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.049435,
	},
	{
		Frame = 281,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.256042,
	},
	{
		Frame = 282,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.46847,
	},
	{
		Frame = 283,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.683764,
	},
	{
		Frame = 285,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.89875,
	},
	{
		Frame = 287,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.109974,
	},
	{
		Frame = 288,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.313517,
	},
	{
		Frame = 289,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.505152,
	},
	{
		Frame = 291,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.680468,
	},
	{
		Frame = 293,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.834881,
	},
	{
		Frame = 294,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.964844,
	},
	{
		Frame = 296,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.071426,
	},
	{
		Frame = 297,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.157017,
	},
	{
		Frame = 298,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.224203,
	},
	{
		Frame = 300,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.275698,
	},
	{
		Frame = 300,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 300,
		Action = "Enable",
		Path = "Lighting.CutOut",
	},
	{
		Frame = 300,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 301,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.RightLines",
	},
	{
		Frame = 301,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.RightLines1",
	},
	{
		Frame = 301,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.Slashh",
	},
	{
		Frame = 301,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.Dust",
	},
	{
		Frame = 302,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.314339,
	},
	{
		Frame = 303,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.343037,
	},
	{
		Frame = 304,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.364746,
	},
	{
		Frame = 304,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Contrast",
		Value = -5,
	},
	{
		Frame = 304,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Saturation",
		Value = -1,
	},
	{
		Frame = 306,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.382469,
	},
	{
		Frame = 308,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.399221,
	},
	{
		Frame = 309,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.418037,
	},
	{
		Frame = 311,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.441969,
	},
	{
		Frame = 312,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.4741,
	},
	{
		Frame = 312,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 312,
		Action = "Disable",
		Path = "Lighting.CutOut",
	},
	{
		Frame = 312,
		Action = "SetProperty",
		Path = "Lighting.CutOut",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 313,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.51754,
	},
	{
		Frame = 315,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.575476,
	},
	{
		Frame = 317,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.651184,
	},
	{
		Frame = 318,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.748077,
	},
	{
		Frame = 319,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.869749,
	},
	{
		Frame = 321,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.020021,
	},
	{
		Frame = 323,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.203049,
	},
	{
		Frame = 324,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.423376,
	},
	{
		Frame = 326,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.690374,
	},
	{
		Frame = 327,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.002827,
	},
	{
		Frame = 328,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.349215,
	},
	{
		Frame = 330,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.717009,
	},
	{
		Frame = 330,
		Action = "Enable",
		Path = "Workspace.Player 7.Highlight",
	},
	{
		Frame = 330,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 1,
	},
	{
		Frame = 330,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 1,
	},
	{
		Frame = 330,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.55,
	},
	{
		Frame = 332,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.092388,
	},
	{
		Frame = 333,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.460058,
	},
	{
		Frame = 334,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.803221,
	},
	{
		Frame = 334,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 0,
	},
	{
		Frame = 334,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 0,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.RightLines",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.RightLines1",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Slashh",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Dust",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.Dust",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.RightLines",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.RightLines1",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 335,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.Slashh",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 336,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.103689,
	},
	{
		Frame = 338,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.342279,
	},
	{
		Frame = 338,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 1,
	},
	{
		Frame = 338,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 1,
	},
	{
		Frame = 339,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.499374,
	},
	{
		Frame = 341,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.555788,
	},
	{
		Frame = 342,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.525408,
	},
	{
		Frame = 342,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 0,
	},
	{
		Frame = 342,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 0,
	},
	{
		Frame = 343,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.314379,
	},
	{
		Frame = 343,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.55,
	},
	{
		Frame = 345,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.755693,
	},
	{
		Frame = 346,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 1,
	},
	{
		Frame = 346,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 1,
	},
	{
		Frame = 347,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.723576,
	},
	{
		Frame = 348,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.167065,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.130459,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.RightLines",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.RightLines1",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Slashh",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Dust",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.Dust",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.RightLines",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.RightLines1",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Player 2.Torso.Slashh",
		Property = "TimeScale",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.Enable.AuraBurst",
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.Enable.AuraBurst2",
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.Enable.AuraBurst3",
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.Enable.Light",
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.Enable.Smoke",
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.Enable.Smoke2",
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.Enable.StripedAir",
	},
	{
		Frame = 349,
		Action = "SetProperty",
		Path = "Workspace.Aura.PointLight",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 349,
		Action = "Enable",
		Path = "Workspace.Aura.PointLight",
	},
	{
		Frame = 350,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 0,
	},
	{
		Frame = 350,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 0,
	},
	{
		Frame = 351,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.404692,
	},
	{
		Frame = 353,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 13.218184,
	},
	{
		Frame = 354,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 9.43842,
	},
	{
		Frame = 354,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 1,
	},
	{
		Frame = 354,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 1,
	},
	{
		Frame = 356,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 7.345831,
	},
	{
		Frame = 357,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 6.253617,
	},
	{
		Frame = 358,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.848093,
	},
	{
		Frame = 358,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 0,
	},
	{
		Frame = 358,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 0,
	},
	{
		Frame = 359,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.3,
	},
	{
		Frame = 359,
		Action = "Disable",
		Path = "Workspace.run streaks.1",
	},
	{
		Frame = 359,
		Action = "SetProperty",
		Path = "Workspace.run streaks.1",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 359,
		Action = "Disable",
		Path = "Workspace.run streaks.2",
	},
	{
		Frame = 359,
		Action = "SetProperty",
		Path = "Workspace.run streaks.2",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 359,
		Action = "Disable",
		Path = "Workspace.run streaks.4",
	},
	{
		Frame = 359,
		Action = "SetProperty",
		Path = "Workspace.run streaks.4",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 359,
		Action = "Disable",
		Path = "Workspace.run streaks.6",
	},
	{
		Frame = 359,
		Action = "SetProperty",
		Path = "Workspace.run streaks.6",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 359,
		Action = "Disable",
		Path = "Workspace.run streaks.7",
	},
	{
		Frame = 359,
		Action = "SetProperty",
		Path = "Workspace.run streaks.7",
		Property = "TimeScale",
		Value = 0.05,
	},
	{
		Frame = 359,
		Action = "SetProperty",
		Path = "Workspace.Aura.PointLight",
		Property = "Brightness",
		Value = 1.46,
	},
	{
		Frame = 360,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.774871,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.730436,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "FillTransparency",
		Value = 0.7,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.Player 7.Highlight",
		Property = "OutlineTransparency",
		Value = 0,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.run streaks.1",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.run streaks.2",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.run streaks.4",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.run streaks.6",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.run streaks.7",
		Property = "TimeScale",
		Value = 1,
	},
	{
		Frame = 363,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.706451,
	},
	{
		Frame = 364,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.695386,
	},
	{
		Frame = 366,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.690083,
	},
	{
		Frame = 368,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.683518,
	},
	{
		Frame = 369,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.668742,
	},
	{
		Frame = 371,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.638999,
	},
	{
		Frame = 372,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.587998,
	},
	{
		Frame = 373,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.512414,
	},
	{
		Frame = 375,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.418033,
	},
	{
		Frame = 377,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.312446,
	},
	{
		Frame = 378,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.202483,
	},
	{
		Frame = 379,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 5.094067,
	},
	{
		Frame = 381,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 4.992215,
	},
	{
		Frame = 383,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 4.901167,
	},
	{
		Frame = 384,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 4.824575,
	},
	{
		Frame = 386,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 4.765739,
	},
	{
		Frame = 387,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 4.727871,
	},
	{
		Frame = 388,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 4.714404,
	},
	{
		Frame = 390,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 13.540714,
	},
	{
		Frame = 392,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.586348,
	},
	{
		Frame = 393,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.576786,
	},
	{
		Frame = 394,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.709274,
	},
	{
		Frame = 396,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.663149,
	},
	{
		Frame = 398,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.548466,
	},
	{
		Frame = 399,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.400713,
	},
	{
		Frame = 401,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.254454,
	},
	{
		Frame = 402,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.142946,
	},
	{
		Frame = 403,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.098585,
	},
	{
		Frame = 405,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.675564,
	},
	{
		Frame = 407,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.313961,
	},
	{
		Frame = 408,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 32.968235,
	},
	{
		Frame = 409,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.624908,
	},
	{
		Frame = 411,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 41.154724,
	},
	{
		Frame = 412,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.11111",
	},
	{
		Frame = 412,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.22222",
	},
	{
		Frame = 412,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.33333",
	},
	{
		Frame = 412,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.34545",
	},
	{
		Frame = 412,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.4444",
	},
	{
		Frame = 412,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.555",
	},
	{
		Frame = 412,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.6",
	},
	{
		Frame = 413,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 46.076778,
	},
	{
		Frame = 414,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 50.284927,
	},
	{
		Frame = 416,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 52.074993,
	},
	{
		Frame = 417,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 51.963181,
	},
	{
		Frame = 418,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 51.620861,
	},
	{
		Frame = 420,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 51.042427,
	},
	{
		Frame = 422,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 50.22908,
	},
	{
		Frame = 423,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 49.18903,
	},
	{
		Frame = 424,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 47.937336,
	},
	{
		Frame = 426,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 46.495144,
	},
	{
		Frame = 428,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 44.888607,
	},
	{
		Frame = 429,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 43.158813,
	},
	{
		Frame = 429,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.3,
	},
	{
		Frame = 431,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 41.387211,
	},
	{
		Frame = 432,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 39.647907,
	},
	{
		Frame = 433,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 37.995678,
	},
	{
		Frame = 435,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.468903,
	},
	{
		Frame = 437,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.093342,
	},
	{
		Frame = 438,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 33.88578,
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.1",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.2",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.3",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.4",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.5",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.6",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.7",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.8",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Workspace.linesss.9",
	},
	{
		Frame = 438,
		Action = "Enable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 439,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 32.857388,
	},
	{
		Frame = 440,
		Action = "Disable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 440,
		Action = "Enable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 441,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 32.009533,
	},
	{
		Frame = 442,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 442,
		Action = "Disable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 443,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 31.317532,
	},
	{
		Frame = 444,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.755865,
	},
	{
		Frame = 444,
		Action = "Disable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 444,
		Action = "Enable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 445,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.173684,
	},
	{
		Frame = 446,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.30406,
	},
	{
		Frame = 446,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.8,
	},
	{
		Frame = 446,
		Action = "Disable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 447,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.945362,
	},
	{
		Frame = 448,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.665733,
	},
	{
		Frame = 450,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.453167,
	},
	{
		Frame = 452,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.297092,
	},
	{
		Frame = 453,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.188034,
	},
	{
		Frame = 454,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.117235,
	},
	{
		Frame = 456,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.076429,
	},
	{
		Frame = 458,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.057652,
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.ddd111",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.ddd322",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.dot2",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.dots1",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.g1",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.impact",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.impact2",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.impact3",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.sta",
	},
	{
		Frame = 458,
		Action = "Enable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.tras",
	},
	{
		Frame = 459,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.053114,
	},
	{
		Frame = 460,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.5,
	},
	{
		Frame = 461,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 34.749672,
	},
	{
		Frame = 461,
		Action = "Enable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 462,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 49.912079,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.Out_Impact",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.Crescents_3",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.Crescents_2",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.Crescents_1",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.8RACS1",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.8RACS",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.7RACS",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.6RACS",
		Amount = 9.45,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.5RACS",
		Amount = 6.75,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.4RAC",
		Amount = 4.05,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.3CA",
		Amount = 4.05,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.2N1",
		Amount = 5,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.1MIDD",
		Amount = 6.75,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.16",
		Amount = 4,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.2.14",
		Amount = 7,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.9",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.8",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.7",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.6",
		Amount = 10,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.5",
		Amount = 2,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.4",
		Amount = 2,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.3",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.2",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.12",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.11",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.10",
		Amount = 10,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.1",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.1.0",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.1",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.2",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.3",
		Amount = 3,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Air",
		Amount = 7,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Air1",
		Amount = 7,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.CleanString",
		Amount = 5,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.CleanString1",
		Amount = 5,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Shocckkk",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Shocckkk1",
		Amount = 1,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Shockwaves1",
		Amount = 5,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Sparks",
		Amount = 10,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Sparks1",
		Amount = 10,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Sparks2",
		Amount = 10,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.Sparks3",
		Amount = 10,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.WindyShockwave",
		Amount = 5,
	},
	{
		Frame = 462,
		Action = "Emit",
		Path = "Workspace.throw.3.decay8",
		Amount = 3,
	},
	{
		Frame = 463,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 60.001686,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Black1",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Black2",
		Amount = 14,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Black25",
		Amount = 7,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Burst",
		Amount = 5,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.DC",
		Amount = 4,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.15",
		Amount = 15,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.16",
		Amount = 15,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Air",
		Amount = 3,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Air1",
		Amount = 4,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Air4",
		Amount = 4,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Air5",
		Amount = 7,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Burst",
		Amount = 1,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Burst1",
		Amount = 1,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Burst2",
		Amount = 1,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Burst3",
		Amount = 5,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Circle",
		Amount = 3,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.CleanString",
		Amount = 5,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.CleanString1",
		Amount = 5,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.DotBig",
		Amount = 20,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.DotBig1",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Flames",
		Amount = 4,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Flames1",
		Amount = 4,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Shockwaves1",
		Amount = 2,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Sparks1",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Sparks3",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Star",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Wind",
		Amount = 2,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Wind2",
		Amount = 7,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Wind3",
		Amount = 2,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Wind4",
		Amount = 5,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.Wind6",
		Amount = 5,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.WindyShockwave",
		Amount = 5,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.decay1",
		Amount = 2,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.decay8",
		Amount = 2,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.flasg",
		Amount = 4,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Lines out.wtrbw",
		Amount = 15,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Smoke",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Sparks",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Sparks1",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Sparks2",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Sparks3",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.Specs",
		Amount = 20,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.embers1",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Emit",
		Path = "Workspace.throw impact.embers2",
		Amount = 10,
	},
	{
		Frame = 463,
		Action = "Disable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 463,
		Action = "Enable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 465,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.577515,
	},
	{
		Frame = 465,
		Action = "Enable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.ddd111",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.ddd322",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.dot2",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.dots1",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.g1",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.impact",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.impact2",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.impact3",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.sta",
	},
	{
		Frame = 465,
		Action = "Disable",
		Path = "Workspace.Player 10.Right Arm.IMPACTFRAMESPARTICLE.tras",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.1",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.2",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.3",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.4",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.5",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.6",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.7",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.8",
	},
	{
		Frame = 466,
		Action = "Disable",
		Path = "Workspace.linesss.9",
	},
	{
		Frame = 467,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 72.505066,
	},
	{
		Frame = 467,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 467,
		Action = "Disable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 468,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.778175,
	},
	{
		Frame = 469,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 78.380844,
	},
	{
		Frame = 469,
		Action = "Disable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 469,
		Action = "Enable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 471,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 78.295563,
	},
	{
		Frame = 471,
		Action = "Enable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 471,
		Action = "Disable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 472,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.11111",
	},
	{
		Frame = 472,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.22222",
	},
	{
		Frame = 472,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.33333",
	},
	{
		Frame = 472,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.34545",
	},
	{
		Frame = 472,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.4444",
	},
	{
		Frame = 472,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.555",
	},
	{
		Frame = 472,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.6",
	},
	{
		Frame = 472,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.5,
	},
	{
		Frame = 473,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 78.067772,
	},
	{
		Frame = 473,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.3,
	},
	{
		Frame = 473,
		Action = "Disable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 474,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 77.739952,
	},
	{
		Frame = 476,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 77.354286,
	},
	{
		Frame = 477,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.951981,
	},
	{
		Frame = 478,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.572884,
	},
	{
		Frame = 480,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.255569,
	},
	{
		Frame = 481,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.037697,
	},
	{
		Frame = 483,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 75.956673,
	},
	{
		Frame = 484,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.03157,
	},
	{
		Frame = 486,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.240723,
	},
	{
		Frame = 488,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.561401,
	},
	{
		Frame = 489,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 76.971184,
	},
	{
		Frame = 491,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 77.447319,
	},
	{
		Frame = 492,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 77.966492,
	},
	{
		Frame = 494,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 78.504364,
	},
	{
		Frame = 495,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 79.035515,
	},
	{
		Frame = 496,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 79.533348,
	},
	{
		Frame = 498,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 79.970215,
	},
	{
		Frame = 499,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.317719,
	},
	{
		Frame = 501,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.547066,
	},
	{
		Frame = 503,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 504,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 506,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 507,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 509,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 510,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 511,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 513,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 514,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
	{
		Frame = 516,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 80.629715,
	},
}

return {
	MaxFrame = MAX_FRAME,
	FPS = FPS,
	Events = EVENTS,
}
