--!strict

export type AwakenAction = "Emit" | "Enable" | "Disable" | "SetProperty" | "MarkerCode"

export type AwakenEvent = {
	Frame: number,
	Action: AwakenAction,
	Path: string?,
	Property: string?,
	Value: any?,
	Amount: number?,
	Code: string?,
}

local MAX_FRAME: number = 574
local FPS: number = 60

local EVENTS: {AwakenEvent} = {
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "AttachToPart",
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.33711051940918,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.19999999999999998,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Saturation",
		Value = -1.350000023841858,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Contrast",
		Value = -10,
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "TintColor",
		Value = {0.24705883825526692, 0.1490196167253991, 1},
	},
	{
		Frame = 0,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Brightness",
		Value = 1,
	},
	{
		Frame = 0,
		Action = "Enable",
		Path = "Lighting.aura",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Lighting.FILTER",
	},
	{
		Frame = 0,
		Action = "Disable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 2,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.071372985839844,
	},
	{
		Frame = 5,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.694177627563477,
	},
	{
		Frame = 7,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.257831573486328,
	},
	{
		Frame = 10,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.808027267456055,
	},
	{
		Frame = 12,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.382294654846191,
	},
	{
		Frame = 14,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.010698318481445,
	},
	{
		Frame = 17,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.717822074890137,
	},
	{
		Frame = 19,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.525476455688477,
	},
	{
		Frame = 22,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.455863952636719,
	},
	{
		Frame = 24,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.459296226501465,
	},
	{
		Frame = 26,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.469429016113281,
	},
	{
		Frame = 29,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.486052513122559,
	},
	{
		Frame = 31,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.508967399597168,
	},
	{
		Frame = 33,
		Action = "MarkerCode",
		Code = "-- Store both parts in a table\nlocal parts = {\n\tworkspace.slip,\n\tworkspace.slipfloor\n}\n\n-- Simple helper function\nlocal function check(a: number?): boolean\n\treturn a ~= nil and a ~= 0\nend\n\n-- Loop through each part\nfor _, part in pairs(parts) do\n\t-- For each descendant of the part\n\tfor _, v: ParticleEmitter? in pairs(part:GetDescendants()) do\n\t\tif not v:IsA(\"ParticleEmitter\") then continue end\n\n\t\tlocal c = v:GetAttribute(\"EmitCount\")\n\t\tlocal du = v:GetAttribute(\"EmitDuration\")\n\n\t\tif check(c) then\n\t\t\tv:Emit(c)\n\t\tend\n\t\tif check(du) then\n\t\t\tv.Enabled = true\n\t\t\ttask.delay(du, function()\n\t\t\t\tv.Enabled = false\n\t\t\tend)\n\t\tend\n\tend\nend",
	},
	{
		Frame = 34,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.537981986999512,
	},
	{
		Frame = 36,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.572922706604004,
	},
	{
		Frame = 38,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.613630294799805,
	},
	{
		Frame = 41,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.65993881225586,
	},
	{
		Frame = 43,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.711711883544922,
	},
	{
		Frame = 46,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.768798828125,
	},
	{
		Frame = 48,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.83106517791748,
	},
	{
		Frame = 50,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.898382186889648,
	},
	{
		Frame = 53,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.970609664916992,
	},
	{
		Frame = 55,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.047625541687012,
	},
	{
		Frame = 58,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.129295349121094,
	},
	{
		Frame = 60,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.21549129486084,
	},
	{
		Frame = 60,
		Action = "MarkerCode",
		Code = "local Workspace = game:GetService(\"Workspace\")\nlocal mapModel = Workspace:WaitForChild(\"Map\")\n\nlocal yOffset = -1000\n\n-- Move all BaseParts inside Map down by 1000 in Y\nfor _, obj in ipairs(mapModel:GetDescendants()) do\n\tif obj:IsA(\"BasePart\") then\n\t\tobj.CFrame = obj.CFrame + Vector3.new(0, yOffset, 0)\n\tend\nend",
	},
	{
		Frame = 62,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.306077003479004,
	},
	{
		Frame = 65,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.400914192199707,
	},
	{
		Frame = 67,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.499863624572754,
	},
	{
		Frame = 70,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.602777481079102,
	},
	{
		Frame = 72,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.709500312805176,
	},
	{
		Frame = 74,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.819864273071289,
	},
	{
		Frame = 77,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.933701515197754,
	},
	{
		Frame = 79,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.050827026367188,
	},
	{
		Frame = 82,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.171045303344727,
	},
	{
		Frame = 84,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.294145584106445,
	},
	{
		Frame = 86,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.419906616210938,
	},
	{
		Frame = 86,
		Action = "Enable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 86,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.frames\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 88,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 88,
		Action = "Disable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 89,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.54808807373047,
	},
	{
		Frame = 90,
		Action = "Enable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 90,
		Action = "Disable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 91,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.678434371948242,
	},
	{
		Frame = 92,
		Action = "Enable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 92,
		Action = "Disable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 94,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.810667037963867,
	},
	{
		Frame = 94,
		Action = "Disable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 96,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.944503784179688,
	},
	{
		Frame = 97,
		Action = "Enable",
		Path = "Lighting.BLACK",
	},
	{
		Frame = 98,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.079620361328125,
	},
	{
		Frame = 99,
		Action = "Enable",
		Path = "Lighting.WHITE",
	},
	{
		Frame = 99,
		Action = "Disable",
		Path = "Lighting.BLACK",
	},
	{
		Frame = 101,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.215688705444336,
	},
	{
		Frame = 101,
		Action = "Enable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 101,
		Action = "Disable",
		Path = "Lighting.WHITE",
	},
	{
		Frame = 101,
		Action = "MarkerCode",
		Code = "local pathOfParticles = game.ReplicatedStorage.Aura\n\nlocal p1 = workspace[\"Player 1\"]\n\n\tfunction check(a: number?): boolean\n\t\treturn a ~= nil and a ~= 0\n\tend\n\nfor _, bodyParts:Humanoid in pairs(p1:GetDescendants()) do\n\tif bodyParts:IsA(\"BasePart\") then\n\t\tif bodyParts.Name == \"HumanoidRootPart\" then continue end\n\t\tfor _, v:ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n\t\t\tif not v:IsA(\"ParticleEmitter\") then continue end\n\n\t\t\tlocal clone = v:Clone()\n\t\t\tclone.Parent = bodyParts\n\n\t\t\tlocal c = clone:GetAttribute(\"EmitCount\")\n\t\t\tlocal du = clone:GetAttribute(\"EmitDuration\")\n\n\t\t\tif check(c) then\n\t\t\t\tclone.Enabled = true\n\t\t\t\ttask.delay(du, function()\n\t\t\t\t\tclone.Enabled = false\n\t\t\t\t\tclone:Destroy()\n\t\t\t\tend)\n\t\t\tend\n\t\tend\n\tend\nend",
	},
	{
		Frame = 103,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.35235023498535,
	},
	{
		Frame = 103,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 103,
		Action = "Disable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 103,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.bigstep\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 105,
		Action = "Enable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 105,
		Action = "Disable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 106,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.489225387573242,
	},
	{
		Frame = 107,
		Action = "Enable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 107,
		Action = "Disable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 108,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.625917434692383,
	},
	{
		Frame = 109,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 109,
		Action = "Disable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 110,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.761991500854492,
	},
	{
		Frame = 111,
		Action = "Enable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 111,
		Action = "Disable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 113,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 17.897003173828125,
	},
	{
		Frame = 113,
		Action = "Disable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 115,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.030479431152344,
	},
	{
		Frame = 118,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.16192054748535,
	},
	{
		Frame = 120,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.290807723999023,
	},
	{
		Frame = 122,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.416595458984375,
	},
	{
		Frame = 125,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.53872299194336,
	},
	{
		Frame = 127,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.656604766845703,
	},
	{
		Frame = 130,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.769641876220703,
	},
	{
		Frame = 132,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.877220153808594,
	},
	{
		Frame = 134,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.97870635986328,
	},
	{
		Frame = 137,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.073467254638672,
	},
	{
		Frame = 139,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.160860061645508,
	},
	{
		Frame = 142,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.24024200439453,
	},
	{
		Frame = 144,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.31097412109375,
	},
	{
		Frame = 146,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.372419357299805,
	},
	{
		Frame = 149,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.42396354675293,
	},
	{
		Frame = 151,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.465009689331055,
	},
	{
		Frame = 154,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.494976043701172,
	},
	{
		Frame = 156,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.513322830200195,
	},
	{
		Frame = 157,
		Action = "SetProperty",
		Path = "Workspace.areafloor",
		Property = "CFrame",
		Value = {-1.4298117673172674, 309.88037751679155, 24.062039382700846, 1, 0, 0, 0, 0, -1, 0, 1, 0},
	},
	{
		Frame = 157,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 50,
	},
	{
		Frame = 157,
		Action = "Enable",
		Path = "Lighting.cutsceneblur",
	},
	{
		Frame = 158,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.519542694091797,
	},
	{
		Frame = 158,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.GoodLines",
	},
	{
		Frame = 158,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.GoodLines1",
	},
	{
		Frame = 158,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Lines1",
	},
	{
		Frame = 158,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Lines2",
	},
	{
		Frame = 158,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Lines",
	},
	{
		Frame = 158,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Speedline",
	},
	{
		Frame = 161,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.510103225708008,
	},
	{
		Frame = 163,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.484989166259766,
	},
	{
		Frame = 166,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.44902229309082,
	},
	{
		Frame = 168,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.407011032104492,
	},
	{
		Frame = 170,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.363704681396484,
	},
	{
		Frame = 173,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.32375717163086,
	},
	{
		Frame = 175,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.291772842407227,
	},
	{
		Frame = 178,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.272287368774414,
	},
	{
		Frame = 179,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 179,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 179,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 180,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.269855499267578,
	},
	{
		Frame = 182,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.28814697265625,
	},
	{
		Frame = 185,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.327226638793945,
	},
	{
		Frame = 187,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.386341094970703,
	},
	{
		Frame = 190,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.464834213256836,
	},
	{
		Frame = 192,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.56214714050293,
	},
	{
		Frame = 194,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.677791595458984,
	},
	{
		Frame = 197,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.81135368347168,
	},
	{
		Frame = 199,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 19.962459564208984,
	},
	{
		Frame = 202,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.130786895751953,
	},
	{
		Frame = 204,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.316030502319336,
	},
	{
		Frame = 204,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 5,
	},
	{
		Frame = 206,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.517925262451172,
	},
	{
		Frame = 209,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.736202239990234,
	},
	{
		Frame = 210,
		Action = "SetProperty",
		Path = "Lighting.Black+Purple",
		Property = "Saturation",
		Value = -1.350000023841858,
	},
	{
		Frame = 211,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 20.970598220825195,
	},
	{
		Frame = 211,
		Action = "SetProperty",
		Path = "Lighting.Black+Purple",
		Property = "Saturation",
		Value = -0.9299999999999999,
	},
	{
		Frame = 211,
		Action = "Enable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 212,
		Action = "SetProperty",
		Path = "Lighting.White+Black",
		Property = "Saturation",
		Value = -1.350000023841858,
	},
	{
		Frame = 213,
		Action = "SetProperty",
		Path = "Lighting.White+Black",
		Property = "Saturation",
		Value = -0.9299999999999999,
	},
	{
		Frame = 213,
		Action = "Enable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 213,
		Action = "Disable",
		Path = "Lighting.Black+Purple",
	},
	{
		Frame = 214,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.220844268798828,
	},
	{
		Frame = 214,
		Action = "SetProperty",
		Path = "Lighting.Black+White",
		Property = "Saturation",
		Value = -1.350000023841858,
	},
	{
		Frame = 214,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.areafloor\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 215,
		Action = "SetProperty",
		Path = "Lighting.Black+White",
		Property = "Saturation",
		Value = -0.8999999999999999,
	},
	{
		Frame = 215,
		Action = "Enable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 215,
		Action = "Disable",
		Path = "Lighting.White+Black",
	},
	{
		Frame = 216,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.48664093017578,
	},
	{
		Frame = 217,
		Action = "Enable",
		Path = "Lighting.WHITE",
	},
	{
		Frame = 217,
		Action = "Disable",
		Path = "Lighting.Black+White",
	},
	{
		Frame = 218,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.76766014099121,
	},
	{
		Frame = 219,
		Action = "Disable",
		Path = "Lighting.WHITE",
	},
	{
		Frame = 221,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.06353759765625,
	},
	{
		Frame = 223,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.373830795288086,
	},
	{
		Frame = 226,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 22.698043823242188,
	},
	{
		Frame = 227,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Brightness",
		Value = -0.15000000596046448,
	},
	{
		Frame = 227,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Saturation",
		Value = -0.6000000238418579,
	},
	{
		Frame = 227,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Contrast",
		Value = 0.20000000298023224,
	},
	{
		Frame = 228,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.03557777404785,
	},
	{
		Frame = 230,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.385738372802734,
	},
	{
		Frame = 233,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 23.747713088989258,
	},
	{
		Frame = 235,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.120542526245117,
	},
	{
		Frame = 238,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.503110885620117,
	},
	{
		Frame = 240,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.89434242248535,
	},
	{
		Frame = 242,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.293807983398438,
	},
	{
		Frame = 245,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 25.70122528076172,
	},
	{
		Frame = 247,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.11625099182129,
	},
	{
		Frame = 250,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.538475036621094,
	},
	{
		Frame = 252,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 26.967432022094727,
	},
	{
		Frame = 254,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.402563095092773,
	},
	{
		Frame = 257,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.843252182006836,
	},
	{
		Frame = 259,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.288776397705078,
	},
	{
		Frame = 262,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 28.738332748413086,
	},
	{
		Frame = 264,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.191024780273438,
	},
	{
		Frame = 266,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 29.645849227905273,
	},
	{
		Frame = 269,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.10169792175293,
	},
	{
		Frame = 271,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 30.557357788085938,
	},
	{
		Frame = 274,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 31.011505126953125,
	},
	{
		Frame = 276,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 31.462692260742188,
	},
	{
		Frame = 278,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 31.909374237060547,
	},
	{
		Frame = 281,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 32.34986877441406,
	},
	{
		Frame = 283,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 32.78242874145508,
	},
	{
		Frame = 286,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 33.20514678955078,
	},
	{
		Frame = 288,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 33.61605453491211,
	},
	{
		Frame = 290,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 34.01308822631836,
	},
	{
		Frame = 293,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 34.39410400390625,
	},
	{
		Frame = 295,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 34.75688934326172,
	},
	{
		Frame = 298,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.09919738769531,
	},
	{
		Frame = 300,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.418766021728516,
	},
	{
		Frame = 302,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.713294982910156,
	},
	{
		Frame = 305,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.980525970458984,
	},
	{
		Frame = 307,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.218257904052734,
	},
	{
		Frame = 310,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.42435073852539,
	},
	{
		Frame = 312,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.59675598144531,
	},
	{
		Frame = 314,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.73359298706055,
	},
	{
		Frame = 317,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.83311080932617,
	},
	{
		Frame = 319,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.89377212524414,
	},
	{
		Frame = 322,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.914249420166016,
	},
	{
		Frame = 324,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.85089111328125,
	},
	{
		Frame = 325,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Light.PointLight",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 325,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.Light.PointLight",
	},
	{
		Frame = 326,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.41320037841797,
	},
	{
		Frame = 327,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.20000000298023224,
	},
	{
		Frame = 329,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 35.27433776855469,
	},
	{
		Frame = 331,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 33.243797302246094,
	},
	{
		Frame = 333,
		Action = "Emit",
		Path = "Workspace.Player 1.Head.Emit.1.C1",
		Amount = 25,
	},
	{
		Frame = 333,
		Action = "Emit",
		Path = "Workspace.Player 1.Head.Emit.1.C2",
		Amount = 5,
	},
	{
		Frame = 333,
		Action = "Emit",
		Path = "Workspace.Player 1.Head.Emit.1.Extra",
		Amount = 15,
	},
	{
		Frame = 333,
		Action = "Emit",
		Path = "Workspace.Player 1.Head.Emit.1.Steam1",
		Amount = 5,
	},
	{
		Frame = 333,
		Action = "Emit",
		Path = "Workspace.Player 1.Head.Emit.1.WindShockwaves",
		Amount = 5,
	},
	{
		Frame = 333,
		Action = "Emit",
		Path = "Workspace.Player 1.Head.Emit.2.Chakra",
		Amount = 8,
	},
	{
		Frame = 333,
		Action = "Emit",
		Path = "Workspace.Player 1.Head.Emit.Star1",
		Amount = 13,
	},
	{
		Frame = 334,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.737823486328125,
	},
	{
		Frame = 334,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.FireSmoke",
	},
	{
		Frame = 334,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.Beams",
	},
	{
		Frame = 334,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.Beams1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Test",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Steam1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Star1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Star",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Specs",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Shock1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Shock2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Set1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L4",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L3",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Extra",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Aura1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Aura",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard3",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Test",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Steam1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Star1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Star",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Specs",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Shock1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Shock2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Set1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L4",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L3",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Extra",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Aura1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Aura",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard3",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.3",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.1",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.2",
	},
	{
		Frame = 335,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.3",
	},
	{
		Frame = 336,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 21.706472396850586,
	},
	{
		Frame = 338,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 18.213470458984375,
	},
	{
		Frame = 341,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.527671813964844,
	},
	{
		Frame = 343,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.498617172241211,
	},
	{
		Frame = 343,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Light.PointLight",
		Property = "Brightness",
		Value = 5,
	},
	{
		Frame = 345,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.7999999999999999,
	},
	{
		Frame = 346,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.877290725708008,
	},
	{
		Frame = 348,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.523988723754883,
	},
	{
		Frame = 350,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.348971366882324,
	},
	{
		Frame = 353,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.285545349121094,
	},
	{
		Frame = 355,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.276531219482422,
	},
	{
		Frame = 358,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.277483940124512,
	},
	{
		Frame = 360,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.284170150756836,
	},
	{
		Frame = 362,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.302343368530273,
	},
	{
		Frame = 365,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.337868690490723,
	},
	{
		Frame = 367,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.39682388305664,
	},
	{
		Frame = 370,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.485676765441895,
	},
	{
		Frame = 370,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.step1\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 372,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.611515998840332,
	},
	{
		Frame = 374,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 14.782384872436523,
	},
	{
		Frame = 377,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.007698059082031,
	},
	{
		Frame = 379,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.29885196685791,
	},
	{
		Frame = 382,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 15.670072555541992,
	},
	{
		Frame = 384,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 16.139617919921875,
	},
	{
		Frame = 384,
		Action = "SetProperty",
		Path = "Workspace.areafloor",
		Property = "CFrame",
		Value = {-1.4298117673172674, 309.88037751679155, 14.383766935320727, 1, 0, 0, 0, 0, -1, 0, 1, 0},
	},
	{
		Frame = 384,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 5,
	},
	{
		Frame = 384,
		Action = "Disable",
		Path = "Lighting.FILTER",
	},
	{
		Frame = 384,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.GoodLines",
	},
	{
		Frame = 384,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.GoodLines1",
	},
	{
		Frame = 384,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Lines1",
	},
	{
		Frame = 384,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Lines2",
	},
	{
		Frame = 384,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Lines",
	},
	{
		Frame = 384,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Speedline",
	},
	{
		Frame = 385,
		Action = "SetProperty",
		Path = "Workspace.Area",
		Property = "CFrame",
		Value = {0.020927429831317644, 312.6447821432092, 4.083466539796178, 1, 0, 0, 0, 1, 0, 0, 0, 1},
	},
	{
		Frame = 385,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Light.PointLight",
		Property = "Brightness",
		Value = 5,
	},
	{
		Frame = 385,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 30,
	},
	{
		Frame = 385,
		Action = "Enable",
		Path = "Workspace.Player 1.Torso.Light.PointLight",
	},
	{
		Frame = 385,
		Action = "Enable",
		Path = "Lighting.FILTER",
	},
	{
		Frame = 385,
		Action = "MarkerCode",
		Code = "-- Store all four parts in a table\nlocal parts = {\n\tworkspace.Lines,\n\tworkspace.slip2,\n\tworkspace.slipfloor2,\n\tworkspace.Area,\n\tworkspace.slip3,\n\tworkspace.slip4\n}\n\n-- Helper function to check attribute validity\nlocal function check(a: number?): boolean\n\treturn a ~= nil and a ~= 0\nend\n\n-- Loop through each part\nfor _, part in pairs(parts) do\n\t-- Loop through all descendants to find ParticleEmitters\n\tfor _, v: ParticleEmitter? in pairs(part:GetDescendants()) do\n\t\tif not v:IsA(\"ParticleEmitter\") then continue end\n\n\t\tlocal c = v:GetAttribute(\"EmitCount\")\n\t\tlocal du = v:GetAttribute(\"EmitDuration\")\n\n\t\tif check(c) then\n\t\t\tv:Emit(c)\n\t\tend\n\t\tif check(du) then\n\t\t\tv.Enabled = true\n\t\t\ttask.delay(du, function()\n\t\t\t\tv.Enabled = false\n\t\t\tend)\n\t\tend\n\tend\nend",
	},
	{
		Frame = 386,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 60.926963806152344,
	},
	{
		Frame = 386,
		Action = "SetProperty",
		Path = "Workspace.Player 1.Torso.Light.PointLight",
		Property = "Brightness",
		Value = 5,
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Test",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Steam1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Star1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Star",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Specs",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Shock1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Shock2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Set1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L4",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L3",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Extra",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Aura1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Aura",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard3",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Test",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Steam1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Star1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Star",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Specs",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Shock1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Shock2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Set1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L4",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L3",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Extra",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Aura1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Aura",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard3",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.3",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.1",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.2",
	},
	{
		Frame = 386,
		Action = "Disable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.3",
	},
	{
		Frame = 389,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 61.42381286621094,
	},
	{
		Frame = 389,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 30,
	},
	{
		Frame = 391,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 61.906402587890625,
	},
	{
		Frame = 394,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 62.37445068359375,
	},
	{
		Frame = 396,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 62.82769012451172,
	},
	{
		Frame = 397,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.step2\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 398,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 63.26587677001953,
	},
	{
		Frame = 401,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 63.68880844116211,
	},
	{
		Frame = 403,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 64.0963363647461,
	},
	{
		Frame = 406,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 64.48832702636719,
	},
	{
		Frame = 408,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 64.86471557617188,
	},
	{
		Frame = 410,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.22542572021484,
	},
	{
		Frame = 413,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.57047271728516,
	},
	{
		Frame = 413,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 5,
	},
	{
		Frame = 415,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.89985656738281,
	},
	{
		Frame = 418,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.21366882324219,
	},
	{
		Frame = 420,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.51197814941406,
	},
	{
		Frame = 422,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.79492950439453,
	},
	{
		Frame = 425,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.06269073486328,
	},
	{
		Frame = 426,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.step3\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 427,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.31543731689453,
	},
	{
		Frame = 430,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.55341339111328,
	},
	{
		Frame = 432,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.77686309814453,
	},
	{
		Frame = 434,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.98609924316406,
	},
	{
		Frame = 437,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.18140411376953,
	},
	{
		Frame = 439,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.3631362915039,
	},
	{
		Frame = 442,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.53164672851562,
	},
	{
		Frame = 444,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.68733215332031,
	},
	{
		Frame = 446,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.83059692382812,
	},
	{
		Frame = 449,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.96187591552734,
	},
	{
		Frame = 451,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.08159637451172,
	},
	{
		Frame = 454,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.19025421142578,
	},
	{
		Frame = 456,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.28829956054688,
	},
	{
		Frame = 458,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.37625122070312,
	},
	{
		Frame = 461,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.45459747314453,
	},
	{
		Frame = 462,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.step4\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 463,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.52386474609375,
	},
	{
		Frame = 466,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.58458709716797,
	},
	{
		Frame = 468,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.6373062133789,
	},
	{
		Frame = 470,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.68256378173828,
	},
	{
		Frame = 473,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.72090911865234,
	},
	{
		Frame = 475,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.7529067993164,
	},
	{
		Frame = 478,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.77912902832031,
	},
	{
		Frame = 479,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Brightness",
		Value = -0.15000000596046448,
	},
	{
		Frame = 479,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Saturation",
		Value = -0.6000000238418579,
	},
	{
		Frame = 479,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Contrast",
		Value = 0.20000000298023224,
	},
	{
		Frame = 480,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.80013275146484,
	},
	{
		Frame = 482,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.8165054321289,
	},
	{
		Frame = 485,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.82880401611328,
	},
	{
		Frame = 487,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.83763122558594,
	},
	{
		Frame = 487,
		Action = "Disable",
		Path = "Workspace.Player 1.Torso.FireSmoke",
	},
	{
		Frame = 487,
		Action = "Disable",
		Path = "Workspace.Player 1.Torso.Beams",
	},
	{
		Frame = 487,
		Action = "Disable",
		Path = "Workspace.Player 1.Torso.Beams1",
	},
	{
		Frame = 490,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.8435287475586,
	},
	{
		Frame = 492,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.84712982177734,
	},
	{
		Frame = 492,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 492,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 492,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "TintColor",
		Value = {1, 1, 1},
	},
	{
		Frame = 492,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 492,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 494,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.84896087646484,
	},
	{
		Frame = 497,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.8496322631836,
	},
	{
		Frame = 498,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 5,
	},
	{
		Frame = 499,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.84973907470703,
	},
	{
		Frame = 499,
		Action = "SetProperty",
		Path = "Workspace.Area",
		Property = "CFrame",
		Value = {0.020927429831317644, 312.6447821432092, -0.04254457489187418, 1, 0, 0, 0, 1, 0, 0, 0, 1},
	},
	{
		Frame = 499,
		Action = "MarkerCode",
		Code = "local pathOfParticles = workspace.step5\n\nfunction check(a: number?): boolean\n  return a ~= nil and a ~= 0\nend\n\nfor _, v: ParticleEmitter? in pairs(pathOfParticles:GetDescendants()) do\n  if not v:IsA(\"ParticleEmitter\") then continue end\n\n  local c = v:GetAttribute(\"EmitCount\")\n  local du = v:GetAttribute(\"EmitDuration\")\n\n  if check(c) then\n    v:Emit(c)\n  end\n  if check(du) then\n    v.Enabled = true\n    task.delay(du, function()\n      v.Enabled = false\n    end)\n  end\nend",
	},
	{
		Frame = 500,
		Action = "SetProperty",
		Path = "Lighting.FILTER",
		Property = "Saturation",
		Value = 0.20000000298023224,
	},
	{
		Frame = 500,
		Action = "SetProperty",
		Path = "Lighting.FILTER",
		Property = "Contrast",
		Value = 0.30000001192092896,
	},
	{
		Frame = 500,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 500,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Contrast",
		Value = -8,
	},
	{
		Frame = 500,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "TintColor",
		Value = {0.3265062661774476, 0.18039215271379383, 1},
	},
	{
		Frame = 500,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Test",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Steam1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Star1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Star",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Specs",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Shock1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Shock2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Set1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L4",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L3",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.L2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Extra",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Aura1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Aura",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard3",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.Attachment.Shard1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Test",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Steam1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Star1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Star",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Specs",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Shock1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Shock2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Set1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L4",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.L3",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Extra",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Aura1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Aura",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard3",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.Attachment.Shard2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye.3",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.1",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.2",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Workspace.Player 1.Head.Eyes.Eye2.3",
	},
	{
		Frame = 500,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 501,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 25,
	},
	{
		Frame = 501,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.GoodLines",
	},
	{
		Frame = 501,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.GoodLines1",
	},
	{
		Frame = 501,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Lines1",
	},
	{
		Frame = 501,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Lines2",
	},
	{
		Frame = 501,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Lines",
	},
	{
		Frame = 501,
		Action = "Enable",
		Path = "Workspace.Cam.CamPart.Speedline",
	},
	{
		Frame = 501,
		Action = "MarkerCode",
		Code = "local Workspace = game:GetService(\"Workspace\")\nlocal mapModel = Workspace:WaitForChild(\"Map\")\n\nlocal yOffset = 1000  -- reverse the downward offset\n\nfor _, obj in ipairs(mapModel:GetDescendants()) do\n\tif obj:IsA(\"BasePart\") then\n\t\tobj.CFrame = obj.CFrame + Vector3.new(0, yOffset, 0)\n\tend\nend",
	},
	{
		Frame = 502,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 24.479358673095703,
	},
	{
		Frame = 503,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.800000011920929,
	},
	{
		Frame = 504,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 27.541980743408203,
	},
	{
		Frame = 506,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 36.74113082885742,
	},
	{
		Frame = 506,
		Action = "SetProperty",
		Path = "Lighting.cutsceneblur",
		Property = "Size",
		Value = 5,
	},
	{
		Frame = 507,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 507,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 507,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "TintColor",
		Value = {1, 1, 1},
	},
	{
		Frame = 507,
		Action = "SetProperty",
		Path = "Lighting.White+Purple",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 507,
		Action = "Enable",
		Path = "Lighting.White+Purple",
	},
	{
		Frame = 509,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 49.23280715942383,
	},
	{
		Frame = 511,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 57.63929748535156,
	},
	{
		Frame = 514,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 64.13623046875,
	},
	{
		Frame = 516,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.00528717041016,
	},
	{
		Frame = 518,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.53607177734375,
	},
	{
		Frame = 518,
		Action = "SetProperty",
		Path = "Lighting.Atmosphere",
		Property = "Density",
		Value = 0.19999999999999998,
	},
	{
		Frame = 521,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.75968933105469,
	},
	{
		Frame = 523,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.73284912109375,
	},
	{
		Frame = 526,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.65579223632812,
	},
	{
		Frame = 528,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.53379821777344,
	},
	{
		Frame = 530,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.37227630615234,
	},
	{
		Frame = 530,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.GoodLines",
	},
	{
		Frame = 530,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.GoodLines1",
	},
	{
		Frame = 530,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Lines1",
	},
	{
		Frame = 530,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Lines2",
	},
	{
		Frame = 530,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Lines",
	},
	{
		Frame = 530,
		Action = "Disable",
		Path = "Workspace.Cam.CamPart.Speedline",
	},
	{
		Frame = 531,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Brightness",
		Value = 0,
	},
	{
		Frame = 531,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 531,
		Action = "SetProperty",
		Path = "Lighting.aura",
		Property = "Contrast",
		Value = 0,
	},
	{
		Frame = 533,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 69.17668151855469,
	},
	{
		Frame = 535,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.95243072509766,
	},
	{
		Frame = 538,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.70494079589844,
	},
	{
		Frame = 540,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.43952178955078,
	},
	{
		Frame = 542,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 68.16140747070312,
	},
	{
		Frame = 545,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.87567138671875,
	},
	{
		Frame = 547,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.58727264404297,
	},
	{
		Frame = 550,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.30101776123047,
	},
	{
		Frame = 552,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 67.02159118652344,
	},
	{
		Frame = 554,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.75353240966797,
	},
	{
		Frame = 557,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.5012435913086,
	},
	{
		Frame = 559,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.26902770996094,
	},
	{
		Frame = 562,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 66.06110382080078,
	},
	{
		Frame = 564,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.88164520263672,
	},
	{
		Frame = 566,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.73475646972656,
	},
	{
		Frame = 569,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.62460327148438,
	},
	{
		Frame = 571,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.55535888671875,
	},
	{
		Frame = 574,
		Action = "SetProperty",
		Path = "Workspace.CurrentCamera",
		Property = "FieldOfView",
		Value = 65.53130340576172,
	},
	{
		Frame = 574,
		Action = "SetProperty",
		Path = "Lighting.FILTER",
		Property = "Saturation",
		Value = 0,
	},
	{
		Frame = 574,
		Action = "SetProperty",
		Path = "Lighting.FILTER",
		Property = "Contrast",
		Value = 0,
	},
}

return {
	MaxFrame = MAX_FRAME,
	FPS = FPS,
	Events = EVENTS,
}
