--!strict

export type AwakenAction = "Emit" | "Enable" | "Disable" | "SetProperty" | "MarkerCode"

export type AwakenEvent = {
	Frame: number,
	Action: AwakenAction,
	Path: string?,
	Property: string?,
	Value: any?,
	Amount: number?,
	Code: string?,
}

local MAX_FRAME: number = 411
local FPS: number = 60

local EVENTS: {AwakenEvent} = {
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Brightness", Value = 0.05 },
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Contrast", Value = 0.5 },
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Saturation", Value = 0.1 },
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "TintColor", Value = {1, 1, 1} },
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 0, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 0, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "AttachToPart", Value = nil },
	{ Frame = 0, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 100.091347 },
	{ Frame = 0, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "FillTransparency", Value = 1 },
	{ Frame = 0, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "OutlineTransparency", Value = 1 },
	{ Frame = 0, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "Enabled", Value = true },
	{ Frame = 0, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "FillTransparency", Value = 0.3 },
	{ Frame = 0, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "OutlineTransparency", Value = 0 },
	{ Frame = 0, Action = "Emit", Path = "Workspace.Player 1.Torso.Body", Amount = 1 },
	{ Frame = 1, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 96.414444 },
	{ Frame = 2, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 87.650726 },
	{ Frame = 3, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 3, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 3, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 3, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 3, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 77.270706 },
	{ Frame = 4, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 67.700905 },
	{ Frame = 5, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 60.036228 },
	{ Frame = 6, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 54.538601 },
	{ Frame = 7, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.181969 },
	{ Frame = 8, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 8, Action = "Emit", Path = "Workspace.VFX.FirstRun.Impact", Amount = 1 },
	{ Frame = 8, Action = "Emit", Path = "Workspace.VFX.FirstRun.Vignette", Amount = 1 },
	{ Frame = 8, Action = "Emit", Path = "Workspace.Player 1.Head.L1", Amount = 1 },
	{ Frame = 8, Action = "Emit", Path = "Workspace.Player 1.Head.R2", Amount = 1 },
	{ Frame = 9, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 10, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 11, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 12, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 12, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "OutlineTransparency", Value = 1 },
	{ Frame = 13, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 14, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 14, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "FillTransparency", Value = 1 },
	{ Frame = 15, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 16, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 17, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 18, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 19, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 20, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 21, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 22, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 23, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 24, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 25, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 26, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 27, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 28, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 29, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 30, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 31, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 32, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 33, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 34, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 35, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 36, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 37, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 38, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 39, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 40, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 41, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 42, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 43, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 44, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 45, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 46, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 47, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 48, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 49, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 50, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 51, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 52, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 53, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 54, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 55, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 56, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 57, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 58, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 59, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 60, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 60, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 60, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 60, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 60, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007538 },
	{ Frame = 61, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 61.858624 },
	{ Frame = 62, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 62, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 62, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 62, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 62, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 61.11385 },
	{ Frame = 63, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.319084 },
	{ Frame = 64, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 57.120598 },
	{ Frame = 65, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 55.059746 },
	{ Frame = 66, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 53.473988 },
	{ Frame = 67, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 67, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 67, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 67, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 67, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 52.33157 },
	{ Frame = 68, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 68, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 68, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 68, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 68, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.542473 },
	{ Frame = 69, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.037178 },
	{ Frame = 70, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.759396 },
	{ Frame = 70, Action = "Emit", Path = "Workspace.l0feu.Head.First_HeadEmit", Amount = 1 },
	{ Frame = 71, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.661194 },
	{ Frame = 72, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.699429 },
	{ Frame = 73, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.833275 },
	{ Frame = 74, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.022457 },
	{ Frame = 75, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.226128 },
	{ Frame = 76, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.402325 },
	{ Frame = 77, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.515415 },
	{ Frame = 78, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.558952 },
	{ Frame = 79, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.534325 },
	{ Frame = 80, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.443398 },
	{ Frame = 81, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.288528 },
	{ Frame = 82, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.072456 },
	{ Frame = 82, Action = "Emit", Path = "Workspace.VFX.FirstRun.CameraZoom", Amount = 1 },
	{ Frame = 83, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.798298 },
	{ Frame = 84, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.469452 },
	{ Frame = 85, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.089569 },
	{ Frame = 86, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 49.662472 },
	{ Frame = 87, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 49.19212 },
	{ Frame = 88, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 48.682529 },
	{ Frame = 89, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 48.13773 },
	{ Frame = 90, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 47.561726 },
	{ Frame = 91, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 46.958473 },
	{ Frame = 92, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 46.331783 },
	{ Frame = 93, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 45.685364 },
	{ Frame = 94, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 45.022743 },
	{ Frame = 95, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.347263 },
	{ Frame = 96, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 43.662075 },
	{ Frame = 97, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 42.970123 },
	{ Frame = 98, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 42.274136 },
	{ Frame = 99, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 41.576622 },
	{ Frame = 100, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 40.879883 },
	{ Frame = 101, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 40.185986 },
	{ Frame = 102, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 39.496822 },
	{ Frame = 103, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 38.814068 },
	{ Frame = 104, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 38.13921 },
	{ Frame = 105, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 37.473553 },
	{ Frame = 106, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 106, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 106, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 106, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 106, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.818253 },
	{ Frame = 107, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.174286 },
	{ Frame = 108, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 35.542503 },
	{ Frame = 109, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 34.923615 },
	{ Frame = 110, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 34.318203 },
	{ Frame = 111, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 33.726753 },
	{ Frame = 112, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 33.149643 },
	{ Frame = 113, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 32.58717 },
	{ Frame = 114, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 32.039539 },
	{ Frame = 115, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 31.506889 },
	{ Frame = 116, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 116, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 116, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 116, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 116, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 30.989302 },
	{ Frame = 117, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 30.486803 },
	{ Frame = 118, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 29.999369 },
	{ Frame = 119, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 30 },
	{ Frame = 119, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = -10 },
	{ Frame = 119, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 119, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 30 },
	{ Frame = 119, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 19.999849 },
	{ Frame = 120, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.005243 },
	{ Frame = 121, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.021278 },
	{ Frame = 121, Action = "Emit", Path = "Workspace.VFX.DashPart.FloorImpact", Amount = 1 },
	{ Frame = 121, Action = "Emit", Path = "Workspace.VFX.DashPart.FloorImpact.BeamsRight", Amount = 1 },
	{ Frame = 121, Action = "Emit", Path = "Workspace.VFX.DashPart.FloorImpact.BeamsMid", Amount = 1 },
	{ Frame = 121, Action = "Emit", Path = "Workspace.VFX.FirstRun.InvertedDistortionOne", Amount = 1 },
	{ Frame = 122, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.047749 },
	{ Frame = 123, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.084478 },
	{ Frame = 124, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.131327 },
	{ Frame = 125, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 30 },
	{ Frame = 125, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = -10 },
	{ Frame = 125, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 125, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 30 },
	{ Frame = 125, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.188175 },
	{ Frame = 126, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.25493 },
	{ Frame = 127, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.33152 },
	{ Frame = 127, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "FillTransparency", Value = 1 },
	{ Frame = 127, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "OutlineTransparency", Value = 1 },
	{ Frame = 128, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 128, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 128, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 128, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 128, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.417902 },
	{ Frame = 129, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.514048 },
	{ Frame = 130, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.619951 },
	{ Frame = 131, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.73563 },
	{ Frame = 132, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.861116 },
	{ Frame = 133, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 20.99646 },
	{ Frame = 134, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 21.141729 },
	{ Frame = 135, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 21.297018 },
	{ Frame = 136, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 21.46242 },
	{ Frame = 137, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 21.638062 },
	{ Frame = 138, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 21.824072 },
	{ Frame = 139, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 22.020609 },
	{ Frame = 140, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 22.227833 },
	{ Frame = 141, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 22.445934 },
	{ Frame = 142, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 22.675102 },
	{ Frame = 143, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 22.91555 },
	{ Frame = 144, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 23.167505 },
	{ Frame = 145, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Brightness", Value = 0.05 },
	{ Frame = 145, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Contrast", Value = 0.5 },
	{ Frame = 145, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Saturation", Value = 0.1 },
	{ Frame = 145, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "TintColor", Value = {1, 1, 1} },
	{ Frame = 145, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 23.4312 },
	{ Frame = 146, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 23.706902 },
	{ Frame = 147, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 23.99486 },
	{ Frame = 148, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 24.295362 },
	{ Frame = 149, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 24.6087 },
	{ Frame = 150, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 24.935179 },
	{ Frame = 151, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 25.275105 },
	{ Frame = 152, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 25.628807 },
	{ Frame = 153, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 25.996618 },
	{ Frame = 154, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 26.37888 },
	{ Frame = 155, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 26.775938 },
	{ Frame = 156, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 27.188145 },
	{ Frame = 157, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 27.615856 },
	{ Frame = 158, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 28.059429 },
	{ Frame = 159, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 28.519222 },
	{ Frame = 160, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 28.995586 },
	{ Frame = 161, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 29.488857 },
	{ Frame = 162, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Brightness", Value = 0.9 },
	{ Frame = 162, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Contrast", Value = 0.5 },
	{ Frame = 162, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Saturation", Value = 0.3 },
	{ Frame = 162, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "TintColor", Value = {1, 0.521569, 0.521569} },
	{ Frame = 162, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 29.999369 },
	{ Frame = 162, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "FillTransparency", Value = 1 },
	{ Frame = 162, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "OutlineTransparency", Value = 1 },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Brightness", Value = 0.05 },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Contrast", Value = 0.5 },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "Saturation", Value = 0.1 },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.ColorCorrection", Property = "TintColor", Value = {1, 1, 1} },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 163, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 163, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 32.347977 },
	{ Frame = 163, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "Enabled", Value = true },
	{ Frame = 163, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "FillTransparency", Value = 0.25 },
	{ Frame = 163, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "OutlineTransparency", Value = 0 },
	{ Frame = 163, Action = "Emit", Path = "Workspace.VFX.DashPart.Left", Amount = 1 },
	{ Frame = 163, Action = "Emit", Path = "Workspace.VFX.DashPart.Right", Amount = 1 },
	{ Frame = 163, Action = "Emit", Path = "Workspace.VFX.DashPart.CamFX.FakeCam", Amount = 1 },
	{ Frame = 163, Action = "Emit", Path = "Workspace.VFX.DashPart.Vignette", Amount = 1 },
	{ Frame = 163, Action = "Emit", Path = "Workspace.VFX.DashPart.InvertedDistortionOne", Amount = 1 },
	{ Frame = 164, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 164, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 164, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 164, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 164, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 34.998245 },
	{ Frame = 165, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 37.905613 },
	{ Frame = 166, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 40.9702 },
	{ Frame = 167, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.014908 },
	{ Frame = 168, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 46.771889 },
	{ Frame = 169, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 48.893967 },
	{ Frame = 170, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 170, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 170, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 170, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 170, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.007458 },
	{ Frame = 171, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 171, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 171, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 171, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 171, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.498421 },
	{ Frame = 172, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 50.978691 },
	{ Frame = 173, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.447842 },
	{ Frame = 174, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 51.905453 },
	{ Frame = 175, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 52.351173 },
	{ Frame = 176, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 176, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 52.784637 },
	{ Frame = 177, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 53.20554 },
	{ Frame = 178, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 53.61359 },
	{ Frame = 179, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 54.008533 },
	{ Frame = 180, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 54.390148 },
	{ Frame = 181, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 54.75827 },
	{ Frame = 182, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 55.112717 },
	{ Frame = 183, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 55.453377 },
	{ Frame = 184, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 55.780186 },
	{ Frame = 185, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 56.093075 },
	{ Frame = 186, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 56.392036 },
	{ Frame = 187, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 56.677094 },
	{ Frame = 188, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 56.948296 },
	{ Frame = 189, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 57.205727 },
	{ Frame = 190, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 57.449516 },
	{ Frame = 191, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 57.679802 },
	{ Frame = 192, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 57.896767 },
	{ Frame = 193, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 58.100628 },
	{ Frame = 194, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 58.291607 },
	{ Frame = 195, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 58.46999 },
	{ Frame = 196, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 58.636047 },
	{ Frame = 197, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 58.790104 },
	{ Frame = 198, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 58.932499 },
	{ Frame = 199, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.063583 },
	{ Frame = 200, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.183735 },
	{ Frame = 201, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.293365 },
	{ Frame = 202, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.392883 },
	{ Frame = 203, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.482719 },
	{ Frame = 204, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.563309 },
	{ Frame = 205, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.635132 },
	{ Frame = 206, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.698631 },
	{ Frame = 207, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.754318 },
	{ Frame = 208, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.802662 },
	{ Frame = 209, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.844177 },
	{ Frame = 210, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.879353 },
	{ Frame = 211, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.908707 },
	{ Frame = 212, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.932762 },
	{ Frame = 213, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.952038 },
	{ Frame = 214, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.96706 },
	{ Frame = 215, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.978348 },
	{ Frame = 216, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.98645 },
	{ Frame = 217, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.991867 },
	{ Frame = 218, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.995159 },
	{ Frame = 219, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.996853 },
	{ Frame = 220, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 220, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.997475 },
	{ Frame = 220, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "FillTransparency", Value = 0.85 },
	{ Frame = 220, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "OutlineTransparency", Value = 0 },
	{ Frame = 221, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 221, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 221, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 221, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 221, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.997562 },
	{ Frame = 221, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "FillTransparency", Value = 1 },
	{ Frame = 221, Action = "SetProperty", Path = "Workspace.l0feu.Highlight", Property = "OutlineTransparency", Value = 1 },
	{ Frame = 222, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "AttachToPart", Value = nil },
	{ Frame = 222, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 59.997444 },
	{ Frame = 222, Action = "SetProperty", Path = "Workspace.Player 1.Highlight", Property = "Enabled", Value = false },
	{ Frame = 223, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804287 },
	{ Frame = 224, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804287 },
	{ Frame = 225, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804291 },
	{ Frame = 226, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804291 },
	{ Frame = 227, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804295 },
	{ Frame = 228, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804302 },
	{ Frame = 229, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804314 },
	{ Frame = 230, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804314 },
	{ Frame = 231, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804321 },
	{ Frame = 232, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804321 },
	{ Frame = 233, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804329 },
	{ Frame = 234, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804329 },
	{ Frame = 235, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.804329 },
	{ Frame = 236, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.526699 },
	{ Frame = 237, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 35.802212 },
	{ Frame = 237, Action = "Emit", Path = "Workspace.VFX.Final.CamFX.FakeCam", Amount = 1 },
	{ Frame = 238, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 34.8013 },
	{ Frame = 239, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 33.6828 },
	{ Frame = 240, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 32.578983 },
	{ Frame = 241, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 31.593267 },
	{ Frame = 242, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 30.805965 },
	{ Frame = 243, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 30.284155 },
	{ Frame = 244, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 30.093843 },
	{ Frame = 244, Action = "Emit", Path = "Workspace.VFX.Steps.LFEmit", Amount = 1 },
	{ Frame = 245, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 30.317715 },
	{ Frame = 246, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 30.945824 },
	{ Frame = 247, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 31.927204 },
	{ Frame = 248, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 33.217457 },
	{ Frame = 249, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 34.764435 },
	{ Frame = 250, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 36.493568 },
	{ Frame = 251, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 251, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 251, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 251, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 251, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 38.292809 },
	{ Frame = 252, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 252, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 252, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 252, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 252, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 40.000225 },
	{ Frame = 252, Action = "Emit", Path = "Workspace.AuraFarmSmoke", Amount = 1 },
	{ Frame = 252, Action = "Emit", Path = "Workspace.VFX.Steps.RFEmit1", Amount = 1 },
	{ Frame = 253, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 41.44149 },
	{ Frame = 254, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 42.582569 },
	{ Frame = 255, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 43.450756 },
	{ Frame = 256, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 256, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 256, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 256, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 256, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.09584 },
	{ Frame = 257, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 257, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 257, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 257, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 257, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.584427 },
	{ Frame = 258, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 259, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 260, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 261, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 262, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 263, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 264, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 265, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 266, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 267, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 268, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 269, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 270, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 271, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 272, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 273, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 274, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 275, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 276, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 277, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 278, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 279, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 280, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 281, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 282, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 283, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 284, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 285, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 286, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 287, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 288, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 289, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 290, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 291, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 292, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 293, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 294, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 295, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 296, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 297, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 298, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 299, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 300, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 301, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 302, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 303, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 304, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 305, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 306, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 307, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 308, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 309, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 310, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 310, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 310, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 310, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 310, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 311, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 311, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 311, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 311, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 311, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 312, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 312, Action = "Emit", Path = "Workspace.l0feu.Head.First_HeadEmit", Amount = 1 },
	{ Frame = 313, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 314, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 10 },
	{ Frame = 314, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 0 },
	{ Frame = 314, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 0 },
	{ Frame = 314, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 10 },
	{ Frame = 314, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 315, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FarIntensity", Value = 0.148 },
	{ Frame = 315, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "FocusDistance", Value = 3.7 },
	{ Frame = 315, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "InFocusRadius", Value = 7 },
	{ Frame = 315, Action = "SetProperty", Path = "Lighting.csDepthOfField", Property = "NearIntensity", Value = 0.574 },
	{ Frame = 315, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 316, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 317, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 318, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 319, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 319, Action = "Emit", Path = "Workspace.VFX.Final.BreatheVFX", Amount = 1 },
	{ Frame = 320, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 321, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 322, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 323, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 324, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 325, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 326, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 327, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 328, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 329, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 330, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 331, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 332, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 333, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 334, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 335, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 336, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 337, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 338, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 339, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 340, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 341, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 342, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 343, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 344, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 345, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 346, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 347, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 348, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 349, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 350, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 351, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 352, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 353, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 354, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 355, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 356, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 357, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 358, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 359, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 360, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 361, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 362, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 363, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 364, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 365, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 366, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 367, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 368, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 369, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 370, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 371, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 372, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 373, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 374, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 375, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 376, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 377, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 378, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 379, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 380, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 381, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 382, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 383, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 384, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 385, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 386, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 387, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 388, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 389, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 390, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 391, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 392, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 393, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 394, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 395, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 396, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 397, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 398, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 399, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 400, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 401, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 402, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 403, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 404, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 405, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 406, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 407, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 408, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 409, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 410, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 411, Action = "SetProperty", Path = "Workspace.CurrentCamera", Property = "FieldOfView", Value = 44.994564 },
	{ Frame = 411, Action = "MarkerCode", Path = "Workspace.VFX", Code = "__ReleaseCamera__" },
}

return {
	FPS = FPS,
	MaxFrame = MAX_FRAME,
	Events = EVENTS,
}


